In [3]:
# let's start with the simplest neural network
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [4]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [5]:
# create a neural network with multiple inputs
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def neural_network(input, weight):
    pred = w_sum(input, weight)
    return pred

weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0]
wlrecs = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

In [6]:
input = [toes[0], wlrecs[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


In [7]:
# numpy code
import numpy as np
weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    prediction = np.dot(input, weights)
    return prediction

input = [toes[0], wlrecs[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


In [8]:
# single input with multiple outputs
def neural_network(input, weights):
    outputs = np.zeros(len(weights))
    for i in range(len(weights)):
        outputs[i] = input * weights[i]
    return outputs

In [9]:
input = wlrecs[0]
pred = neural_network(input, weights)
print(pred)

[0.065 0.13  0.   ]


In [25]:
weights = np.array([
    [0.1, 0.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
])
inputs = np.array([toes[0], wlrecs[0], nfans[0]])

In [59]:
# neural network with multiple inputs and outputs
def vect_mat_mul(a, b):
    outputs = np.zeros(len(a))
    for i in range(len(weights)):
        outputs[i] = w_sum(a, b[i])
    return outputs

def neural_network(inputs, weights):
    hidden = vect_mat_mul(inputs, weights)
    pred = vect_mat_mul(hidden, weights)
    return pred

# testing our neural network
print(neural_network(inputs, weights))

[-0.136   0.2515  1.3705]


In [60]:
a = np.array([1, 2, 3, 4])
b = np.random.randint(1, 10, (2, 4))
a, b

(array([1, 2, 3, 4]),
 array([[8, 5, 7, 2],
        [4, 1, 5, 4]]))

In [61]:
a * b

array([[ 8, 10, 21,  8],
       [ 4,  2, 15, 16]])