In [12]:
# neural network
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

# to sum all the weights
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

# element wise multiplication
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

In [6]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

weights = [0.1, 0.2, -.1]

win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]

input = [toes[0], wlrec[0], nfans[0]]

In [7]:
pred = neural_network(input, weights)
pred

0.8600000000000001

In [8]:
error = (pred - true) ** 2
error

0.01959999999999997

In [13]:
delta = pred - true
print(delta) # delta

weight_deltas = ele_mul(delta, input)
print("weights: ", weights) # weights
print("weight deltas: ", weight_deltas) # weight deltas

-0.1399999999999999
weights:  [0.1, 0.2, -0.1]
weight deltas:  [-1.189999999999999, -0.09099999999999994, -0.16799999999999987]


In [15]:
alpha = 0.01

# update weights
for i in range(len(weights)):
    weights[i] -= weight_deltas[i] * alpha

print("updated weights: ", weights)

updated weights:  [0.1238, 0.20182, -0.09664]


In [1]:
import numpy as np

vect1 = [1, 2, 3]
vect2 = [4, 5, 6]

np.outer(vect1, vect2)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

np.dot(a, b)

30

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)
print(b)
np.dot(a, b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [6]:
a @ b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [8]:
np.inner(a, b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])