### Basic Matrices Operations

In [1]:
import numpy as np

# initialize matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [6]:
A, B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]))

In [2]:
np.inner(A, B)

array([[ 46,  28,  10],
       [118,  73,  28],
       [190, 118,  46]])

In [4]:
np.dot(A, B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [5]:
A @ B

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])